### ISSUE TITLE
Broken link: Corpus data inaccessible

### ISSUE THREAD

**Issue by AntonioDLC** [anlausch/sciarg_resource_analysis#2]
The URL http://data.dws.informatik.uni-mannheim.de/sci-arg/compiled_corpus.zip to download the corpus doesn't work.

**Comment by anlausch** [comment]
I just tested it myself and it worked.

**Comment by AntonioDLC** [comment]
I tried it yesterday several times with no success and today too once, right before opening this issue.
Not reopening, you are right. It is working right now.
